// models/Recipe.js — Chef's Diary Recipe Schema
//
// This model has two equal-priority layers:
//   1. The technical recipe (ingredients, steps, timing, difficulty)
//   2. The emotional recipe (story, dedication, cultural origin, family legacy)
//
// Most recipe platforms treat the emotional layer as an afterthought —
// a single "description" field bolted on. Here, EmotionalContextSchema,
// DedicationSchema, and FamilyLegacySchema are first-class citizens
// with their own structured fields. This shapes how Groq AI prompts
// are engineered later — the model knows exactly which fields to fill.
//
// DESIGN DECISIONS:
//   - ingredients[] and steps[] are EMBEDDED: bounded, always fetched together.
//   - likes[] is an EMBEDDED array of ObjectIds. At project scale (<10,000 likes/recipe)
//     this is fine. A comment marks when to extract to a Reaction collection.
//   - comments are NOT embedded — they live in Comment.js and are paginated.
//   - slug is auto-generated from title in a pre-save hook.

import mongoose from 'mongoose';

const { Schema } = mongoose;

// ─────────────────────────────────────────────────────────────────────────
// SUB-SCHEMAS
// ─────────────────────────────────────────────────────────────────────────

// One row in the ingredient list
const IngredientSchema = new Schema({
  name:       { type: String, required: true, trim: true },
  quantity:   { type: String, required: true },  // "2", "1/2", "a handful"
  unit:       { type: String, default: '' },      // "cups", "grams", "tbsp"
  notes:      { type: String, default: '' },      // "roughly chopped", "room temperature"
  isOptional: { type: Boolean, default: false },
  // Cached AI substitution — populated by the Groq service on demand.
  // Stored here so we don't call Groq for the same substitution twice.
  aiSubstitutionCache: { type: String, default: '' },
}, { _id: false });

// One cooking step
const StepSchema = new Schema({
  order:       { type: Number, required: true },
  instruction: { type: String, required: true, maxlength: 1500 },
  duration:    { type: String, default: '' },     // "15 minutes", "until golden"
  technique:   { type: String, default: '' },     // "fold gently", "deglaze"
  tips:        { type: String, default: '' },     // "Don't overcrowd the pan"
  mediaUrl:    { type: String, default: '' },     // Step-specific photo
  isKeyStep:   { type: Boolean, default: false }, // Highlighted as a critical step
}, { _id: true });

// A photo or video in the recipe's gallery
const MediaItemSchema = new Schema({
  url:     { type: String, required: true },
  type:    { type: String, enum: ['image', 'video'], default: 'image' },
  caption: { type: String, default: '', maxlength: 200 },
  isCover: { type: Boolean, default: false }, // Marks the hero image
}, { _id: false });

// ── The Emotional Heart of Chef's Diary ──────────────────────────────────
// This schema is what differentiates Chef's Diary from every other recipe platform.
// It captures the human experience behind the dish.
const EmotionalContextSchema = new Schema({
  // The personal narrative — can be written by the user or AI-assisted via Groq
  story: { type: String, default: '', maxlength: 3000 },

  // Structured mood tags drive the AI's storytelling tone
  mood: {
    type:    String,
    enum:    ['nostalgic', 'celebratory', 'comforting', 'adventurous', 'healing', 'romantic', 'spiritual', 'playful', ''],
    default: '',
  },

  // Cultural and geographic roots of the dish
  culturalOrigin: { type: String, default: '', trim: true }, // "Hyderabadi", "Sicilian"
  regionOfOrigin: { type: String, default: '', trim: true }, // "Southern Italy"
  countryOfOrigin:{ type: String, default: '', trim: true }, // "India"

  // Temporal context — when this dish belongs
  season:   { type: String, enum: ['spring', 'summer', 'autumn', 'winter', 'year-round', ''], default: '' },
  occasion: { type: String, default: '', maxlength: 100 }, // "Eid morning", "Sunday brunch"

  // Was this story generated by Groq AI, or written by the user?
  // Displayed as a small "AI-assisted" badge on the recipe card
  isAIGenerated: { type: Boolean, default: false },
}, { _id: false });

// A personal dedication — "For my Nani, who made this every Diwali"
// The most uniquely human feature in the platform
const DedicationSchema = new Schema({
  dedicatedTo:  { type: String, default: '', maxlength: 100 }, // "Nani"
  relationship: { type: String, default: '', maxlength: 60  }, // "grandmother"
  message:      { type: String, default: '', maxlength: 400 }, // The heartfelt note
}, { _id: false });

// Heirloom / family recipe tracking
// Answers: "How old is this recipe? Who carried it forward?"
const FamilyLegacySchema = new Schema({
  isHeirloom:          { type: Boolean, default: false },
  estimatedGeneration: { type: Number, default: null }, // "3rd generation recipe"
  originStory:         { type: String, default: '', maxlength: 500 },
  familyName:          { type: String, default: '', maxlength: 100 }, // "The Sharma Family Recipe"
}, { _id: false });

// ─────────────────────────────────────────────────────────────────────────
// MAIN RECIPE SCHEMA
// ─────────────────────────────────────────────────────────────────────────

const RecipeSchema = new Schema(
  {
    // ── Core Identity ────────────────────────────────────────────────────
    author:      { type: Schema.Types.ObjectId, ref: 'User', required: true },
    title:       { type: String, required: true, trim: true, maxlength: 150 },
    slug:        { type: String, unique: true },   // URL-safe version of title — auto-generated
    description: { type: String, maxlength: 600, default: '' },

    // ── Media ────────────────────────────────────────────────────────────
    coverImageUrl: { type: String, default: '' },
    mediaGallery:  [MediaItemSchema],

    // ── Technical Recipe Data ────────────────────────────────────────────
    ingredients: [IngredientSchema],
    steps:       [StepSchema],

    servings:  { type: Number, default: 4, min: 1 },
    prepTime:  { type: Number, default: null }, // minutes
    cookTime:  { type: Number, default: null }, // minutes
    restTime:  { type: Number, default: null }, // minutes (marinating, cooling, resting)
    totalTime: { type: Number, default: null }, // auto-computed in pre-save

    difficulty: {
      type:    String,
      enum:    ['beginner', 'intermediate', 'advanced', 'professional'],
      default: 'beginner',
    },

    cuisineType:  [{ type: String, trim: true }], // ["Indian", "Fusion"]
    dietaryTags:  [{ type: String, trim: true }], // ["vegan", "gluten-free"]
    tags:         [{ type: String, trim: true }], // ["#comfortfood", "#quickmeal"]

    // ── The Emotional Layer ───────────────────────────────────────────────
    // default: () => ({}) creates a fresh empty object for each recipe
    // instead of sharing a single default object across all documents (a JS gotcha).
    emotionalContext: { type: EmotionalContextSchema, default: () => ({}) },
    dedication:       { type: DedicationSchema,       default: () => ({}) },
    familyLegacy:     { type: FamilyLegacySchema,     default: () => ({}) },

    // ── Social Metrics ────────────────────────────────────────────────────
    // SCALING NOTE: The `likes` array stores user ObjectIds.
    // At 12 bytes each, 10,000 likes = 120KB — acceptable for this stage.
    // When any recipe consistently exceeds ~8,000 likes, migrate to a
    // separate Reaction collection (indexed on targetId + userId).
    likes:        [{ type: Schema.Types.ObjectId, ref: 'User' }],
    likeCount:    { type: Number, default: 0, min: 0 }, // Denormalized
    saveCount:    { type: Number, default: 0, min: 0 },
    commentCount: { type: Number, default: 0, min: 0 }, // Incremented by Comment model
    viewCount:    { type: Number, default: 0, min: 0 },

    // ── AI Metadata ───────────────────────────────────────────────────────
    aiGeneratedStory:   { type: Boolean, default: false },
    // Map type stores key-value pairs: { "butter": "coconut oil", "milk": "oat milk" }
    // Used to cache Groq substitution results so we don't repeat the same API call.
    aiSubstitutionCache:{ type: Map, of: String, default: () => new Map() },

    // ── Status & Visibility ───────────────────────────────────────────────
    status: {
      type:    String,
      enum:    ['draft', 'published', 'archived'],
      default: 'draft',
    },
    visibility: {
      type:    String,
      enum:    ['public', 'connections_only', 'private'],
      default: 'public',
    },
  },
  { timestamps: true }
);

// ─────────────────────────────────────────────────────────────────────────
// PRE-SAVE MIDDLEWARE
// ─────────────────────────────────────────────────────────────────────────

RecipeSchema.pre('save', async function (next) {
  // ── Auto-generate slug from title ──────────────────────────────────────
  // Only regenerate if the title has changed (or this is a new document)
  if (this.isModified('title') || !this.slug) {
    const baseSlug = this.title
      .toLowerCase()
      .normalize('NFD')                   // Decompose accents: "café" → "cafe"
      .replace(/[\u0300-\u036f]/g, '')    // Remove accent marks
      .replace(/[^a-z0-9\s-]/g, '')      // Remove non-alphanumeric characters
      .replace(/\s+/g, '-')               // Replace spaces with hyphens
      .replace(/-+/g, '-')               // Collapse multiple hyphens
      .trim();

    // Check for slug collision and append a short timestamp suffix if needed
    // This handles cases where two chefs both post a "Chocolate Cake" recipe
    const existing = await mongoose.model('Recipe').findOne({
      slug: baseSlug,
      _id:  { $ne: this._id }, // Exclude the current document (for updates)
    });

    this.slug = existing ? `${baseSlug}-${Date.now().toString(36)}` : baseSlug;
  }

  // ── Auto-compute totalTime ─────────────────────────────────────────────
  const prep  = this.prepTime  || 0;
  const cook  = this.cookTime  || 0;
  const rest  = this.restTime  || 0;
  if (prep || cook || rest) {
    this.totalTime = prep + cook + rest;
  }

  next();
});

// ─────────────────────────────────────────────────────────────────────────
// INDEXES
// ─────────────────────────────────────────────────────────────────────────

// Full-text search across recipe discovery fields
RecipeSchema.index(
  {
    title:                           'text',
    tags:                            'text',
    cuisineType:                     'text',
    'emotionalContext.culturalOrigin':'text',
    description:                     'text',
  },
  {
    weights: { title: 10, cuisineType: 5, tags: 4, 'emotionalContext.culturalOrigin': 3, description: 1 },
    name: 'recipe_text_search',
  }
);

RecipeSchema.index({ author: 1, status: 1 });              // "All published recipes by this chef"
RecipeSchema.index({ likeCount: -1, createdAt: -1 });      // Trending recipes feed
RecipeSchema.index({ status: 1, visibility: 1, createdAt: -1 }); // Main public feed query
RecipeSchema.index({ cuisineType: 1, status: 1 });         // Filter by cuisine
RecipeSchema.index({ dietaryTags: 1, status: 1 });         // Filter by dietary tag
RecipeSchema.index({ slug: 1 });                           // Recipe page URL lookup

export default mongoose.model('Recipe', RecipeSchema);